themes:
  - name: "Kanagawa"
    colors:
      - "#DCD7BA"
      - "#C8C093"
      - "#16161D"
      - "#1F1F28"
      - "#2A2A37"
      - "#363646"
      - "#54546D"
      - "#223249"
      - "#2D4F67"
      - "#2B3328"
      - "#49443C"
      - "#74C7EC"
      - "#43242B"
      - "#252535"
      - "#76946A"
      - "#C34043"
      - "#DCA561"
      - "#E82424"
      - "#FF9E3B"
      - "#6A9589"
      - "#658594"
      - "#938AA9"
      - "#957FB8"
      - "#7E9CD8"
      - "#9CABCA"
      - "#7FB4CA"
      - "#A3D4D5"
      - "#7AA89F"
      - "#98BB6C"
      - "#938056"
      - "#C0A36E"
      - "#E6C384"
      - "#D27E99"
      - "#E46876"
      - "#FF5D62"
      - "#FFA066"
      - "#717C7C"
